version: '3.9'

services:
  db:
    image: postgres:16
    container_name: fintrans-postgres
    restart: always
    environment:
      POSTGRES_USER: fintrans
      POSTGRES_PASSWORD: fintrans123
      POSTGRES_DB: fintrans_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fintrans-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: